### ISSUE TITLE
Visual Bug : Choose IRQ for WIFI with 2 digits then choose one with 1 digit.

### ISSUE THREAD

**Issue by jdredd87** [FreddyVRetro/ISA-PicoMEM#18]
PicoMem v1.11
May 28 firmware

Visual Bug : Choose IRQ for WIFI with 2 digits then choose one with 1 digit.

So if you pick 10 , then change it to 5, it will show 50 on the screen. Just not clearing out char after the 5.

**Comment by FreddyVRetro** [comment]
Corrected, I removed IRQ 9 and 10 :)
