### ISSUE TITLE
New test scenario

### ISSUE THREAD

**Issue by thbreidenbach** [FreddyVRetro/ISA-PicoMEM#2]
Hi there, 
over on a1k.org I learned about PicoMEM. For one reason this project seems interesting for the Amiga Community. 
Amiga Big Box Computers have ISA Slots in line with the Amiga Zorro Bus which are utilized through Bridgeboards that act like SBC with a Bridge between DOS and Amiga to exchange data and share Hardware.

Bridgeboards vary from e.g. 8088 up to 486sx alike. Since PicoMEM offers Drive(s)/Mouse and RAM in one it is like a game changer since the amount of usable ISA Slots is limited to max 3 in the Amiga Computers. The typical scenario is Sound/VGA and Mass Storage. Together with the Bridge which obviously takes one slot theres nothing left when sharing the Amiga Mouse doesn't work as expected (which happens occasionally)

I filled in the form and would like to contribute compatibility information for the different Bridgeboards. I currently have a A2088, A2386sx and a Vortex Golden Gate 486slc2 which I could test against. Others on A1k can contribute too.

Hardware development for the Amiga Computers is extremely active. PCB or Gerbers provided I could build a board to save your time.

Best Thorsten

**Comment by FreddyVRetro** [comment]
Hi,
The PicoMEM was testes as working on an A2286 Board.
You need to take the C8 base address as D000 is reserved by the Amiga.
