### ISSUE TITLE
No SD card when setting up new HDD image

### ISSUE THREAD

**Issue by jdredd87** [FreddyVRetro/ISA-PicoMEM#22]
PicoMem v1.11
May 28 firmware

IBM Model 30 - 8086

When creating an HDD ( and maybe floppy ) image, but there is no SD card inserted.
It seems to not care and no errors or warnings when it "Creates" the image.
Does not seem to care that there is no microSD card in there / no HDD folder.

But if you got to select an image to boot up, it does care.

**Comment by FreddyVRetro** [comment]
Hi,

This is something I need to correct.

**Comment by FreddyVRetro** [comment]
Corrected in the next firmware
