### ISSUE TITLE
BIOS Setup Tool not usable on mono-chrome devices

### ISSUE THREAD

**Issue by a3nw3n** [FreddyVRetro/ISA-PicoMEM#27]
I try to use the picomem Card on an ancient Olivetti M24, which in general seems to work fine.

But as this 8086 device only has a text / green monochrome display, the UI of the setup tool is barely usable. The the brightness or contrast dials sadly have no effect.

Is there some config option to use an b/w mode or other colors scheme with more contrast?

Just by guessing the keystrokes I managed to get it working, but changing disks is hardly possible.

Thanks!

![IMG_1494](https://github.com/FreddyVRetro/ISA-PicoMEM/assets/146955281/02c9eabb-abf1-4fae-b64e-536d5579049b)

![IMG_1493](https://github.com/FreddyVRetro/ISA-PicoMEM/assets/146955281/b0f66325-7959-43b7-925a-8e8a9a8eef6d)

![IMG_1495](https://github.com/FreddyVRetro/ISA-PicoMEM/assets/146955281/a20c91d3-51de-4811-b123-16acc9eaed04)

**Comment by jschulbach** [comment]
Amazing, I literally hit this same issue this weekend trying out the picomem on my PC 6300(rebadge of the Olivetti M24). I'm seeing the same missing text on my CRT 313/H monochrome display. Came here to report an issue and you beat me to it!

**Comment by vkoskiv** [comment]
Encountered this exact same thing just now with my 5151 and a Video-7 VEGA card set to MDA mode

**Comment by nikolarun** [comment]
Just had the same issue on a 8086 NEC V40 with a Trident 9000c with VGA on a LCD monitor. Would love to know if there is a config i can use

**Comment by FreddyVRetro** [comment]
Hi,

In next firmware release I will compile one with the "Light blue on Grey" color changed (it is the one not visible)

**Comment by nikolarun** [comment]
> Just had the same issue on a 8086 NEC V40 with a Trident 9000c with VGA on a LCD monitor. Would love to know if there is a config i can use

My issue turned out to be completely unrelated. when taking the case off to install the card , i had changed the switch for the video output on the integrated CGI to Colour, once I switched it back to Mono it was fine. ( I had no idea that that switch impacted my ISA Vga card... )

**Comment by FreddyVRetro** [comment]
Hi,

If you read this, I released a variant of the firmware for Monochrome screens.
Can you test it please ? :)

**Comment by jschulbach** [comment]
Looks good on my PC 6300 so far. Will test further this evening.

![IMG_3109](https://github.com/user-attachments/assets/8e3d5b97-39c4-47d0-ba23-1ef8c7de02ef)
![IMG_3110](https://github.com/user-attachments/assets/0471778a-a0aa-46b2-b4b9-a2d5695fc6fc)
![IMG_3107](https://github.com/user-attachments/assets/5a96cdee-8813-46da-b582-0577f7a0e692)

**Comment by JeffWDH** [comment]
@FreddyVRetro would it be possible to get a monochrome release of the Oct 5th firmware? Thanks!

**Comment by FreddyVRetro** [comment]
> @FreddyVRetro would it be possible to get a monochrome release of the Oct 5th firmware? Thanks!

@JeffWDH Yes of course, I will try to not forget
Later, I hope to do it selectable in the BIOS itself.
