### ISSUE TITLE
IBM 5150 - not seeing option to enter PicoMEM BIOS

### ISSUE THREAD

**Issue by JeffWDH** [FreddyVRetro/ISA-PicoMEM#30]
Firmware: PM_W_Jul16_MD.uf2

I just received this PicoMEM and installed it into an IBM 5150. I'm not getting an option to enter the PicoMEM BIOS at boot and the system goes straight into BASIC. I've tried a line with "PREBOOT" to config.txt but that doesn't seem to do anything. 

Any advice?
Thanks!

**Comment by JeffWDH** [comment]
Just as a sanity check, do you think I'm running up against this:

```
Symptom 	Does not work in an early IBM 5150 (IBM PC).
Background 	The XT-IDE card uses a 'BIOS expansion ROM' (the EEPROM on the card) (a.k.a. BIOS ROM) (a.k.a. boot ROM) (a.k.a. option ROM).
Cause 	        The motherboard BIOS supplied in an early IBM 5150 does not support BIOS expansion ROM's.
Fix            	Upgrade the motherboard BIOS to the final one (revision 10/27/82).  That BIOS supports BIOS expansion ROM's.
```
https://minuszerodegrees.net/xtide/XT-IDE%20-%20Problems.htm

**Comment by FreddyVRetro** [comment]
Hi,
Picomem bios is also an expansion ROM, so I think yes.

**Comment by JeffWDH** [comment]
Can confirm, the 10/27/82 BIOS is the fix.

**Comment by FreddyVRetro** [comment]
Thanks for your help, entry added to the Wiki
