### ISSUE TITLE
[enhancement] no-bios no-irq operation mode (for having UMB and EMS only)

### ISSUE THREAD

**Issue by pawosm-arm** [FreddyVRetro/ISA-PicoMEM#31]
When the IRQ jumper is removed, no IRQ is being used, hence IRQ-demanding functionalities aren't available. And there are use cases where this is desirable.
Also, the address 0 can be set for BIOS, so no BIOS functionalities will be accessible from the PC. And this is something that puzzles me. What is the current use case for setting address 0?
From what I am experiencing, the card becomes entirely unusable and only occupying the ISA slot with BIOS address set to 0. 
What I expected was that the functionalities that are not requiring BIOS could still be available, thus disabling BIOS would prevent PicoMEM from using a precious part of the upper address space.
In the end, the lo-tech's UMB and EMS cards did not require BIOS neither they needed IRQ for operation. The UMB card had its dip switches to setup the upper memory segment, the EMS card had its dip switches to setup I/O port. And that's it.
I suspect, with firmware modification, PicoMEM could also be able to work like that: disable disk/floppy, network, audio and USB host, enable EMS and UMB only, and once configured that way, the BIOS memory address could be set to 0, so the BIOS functionality wouldn't be visible to the PC.
In the end, my primary goal that brought my attention to PicoMEM was to have the UMB and EMS on a single one ISA card, and nothing more.

**Comment by FreddyVRetro** [comment]
Hi,
No BIOS mode is something planned, but taking time as long to code and not a priority.

It is more planned to have the picomem in I/O only than to do RAM
