### ISSUE TITLE
PCI bus

### ISSUE THREAD

**Issue by alexartwww** [FreddyVRetro/ISA-PicoMEM#32]
Why didn't you add PCI port from the other side of this card?

E.g. it could be useful if I want to install OS on powerful PC and then insert it to 286.

Is it possible?

**Comment by megatog615** [comment]
Not what I expected from the title but it would be nice if the picomem had support for 16 or 32-bit buses like 16-bit ISA or 32-bit PCI or even VLB(but I'm not holding out for that one).

**Comment by FreddyVRetro** [comment]
Can t be done

**Comment by mcgurk** [comment]
Just install OS with powerful PC and read drive to imagefile to microSD-card with modern PC.

If more powerful PC includes IDE, use cheap CF-IDE-adapter and CF-card.
If more powerful PC includes SATA, use cheap USB-SATA-adapter.

Even easier is to install OS with modern PC and modern OS with virtual machine or emulator.
