### ISSUE TITLE
WinImage Cannot Open Image Created by PicoMem

### ISSUE THREAD

**Issue by jkmills78** [FreddyVRetro/ISA-PicoMEM#33]
Firmware: PM_W_Jul16_FR
Hardware: v1.11

I am unable to open the images created by the PicoMem in WinImage.  It states that it is not an image file.  However, the images hosted in your repository (i.e D33_200M_EN) can be opened.  This seems like an issue with the way the PicoMem is creating the images, and is preventing me from being able to transfer a "large" amount of data to the new hard drive image.

**Comment by FreddyVRetro** [comment]
Hi,

It is possible that winimage don t see small hdd image due to different CHS.

You can mount 2 images and transfer the files like this.
