### ISSUE TITLE
PCM5102 Adlib Instructions

### ISSUE THREAD

**Issue by SanPollo** [FreddyVRetro/ISA-PicoMEM#38]
I have bought a PCM5102 board to connect to my PicoMEM for Adlib emulation.

However, I saw on a [ctrl-alt-rees video](https://youtu.be/RACp9P-KUVE?si=MG2EdrXGC90rZ4XP&t=36) that the board must be modified with a soldering iron to work with the PicoMEM. Unfortunately, I can't find any instructions in the repo, or on the wiki.

Please would you provide instructions for modifying/configuring the PCM5102 to work with the PicoMEM, and also update the documentation on the wiki?

**Comment by xinteksik** [comment]
![image](https://github.com/user-attachments/assets/28783348-396a-41b0-acd6-205652fa6ae5)

![image](https://github.com/user-attachments/assets/2028faab-b6cd-4d2a-ab01-6652944a5a36)

**Comment by FreddyVRetro** [comment]
I added an audio section in the Wiki

**Comment by SanPollo** [comment]
Thanks both!
