### ISSUE TITLE
Southamerica Distribution of ISA-PicoMEM

### ISSUE THREAD

**Issue by nsinav** [FreddyVRetro/ISA-PicoMEM#39]
Hello:

Hi, I'm sorry to write to you through this medium, but it's the only way I found. I'm interested in distributing this product in South America. Is this possible? Thank you in advance for your reply.

**Comment by FreddyVRetro** [comment]
Hi,
I promiced exclusive distribution to Texelec for America, sorry :-(

**Comment by nsinav** [comment]
Hello. I understand. And maybe distribution only in Chile? (My country). I think Kevin Williams does not care about South América, maybe i can talk with him, i got the distribution for PETSCII Robots and Planet X3 from his partner David Murray. But I prefer to keep the local market, as it is a good market for retro hardware. I am really interested. Kind regards,

**Comment by iosoft** [comment]
why not sell directly through eBay International?
