### ISSUE TITLE
Feature Request: Config File Editor

### ISSUE THREAD

**Issue by jkmills78** [FreddyVRetro/ISA-PicoMEM#40]
I would like to see if there is a possibility of adding an editor for the config file.  The benefit would be that changes could be made to the config without having to remove the SD card, unless of course the changes prevent the machine from booting.  It can be a hassle to remove the SD card from the back of a machine.  The way I would picture this working would be individual fields for each config setting, which upon saving would be written out to the config.txt file.  After saving I imagine a forced reboot would be required.

**Comment by FreddyVRetro** [comment]
Hi,
I will start to work something like this in one or two months (mount the MicroSD to DOS)
