### ISSUE TITLE
Create new floppy image in PicoMEM

### ISSUE THREAD

**Issue by henrikstengaard** [FreddyVRetro/ISA-PicoMEM#44]
I found a driver disk image as an exe file on the web that wanted to write to floppy and since I didn't have an option in PicoMEM BIOS to create a new floppy image, I had to use another existing floppy image overwriting its content. Not a big issue, but had to copy that overwritten floppy image again to the SD-card.

The functionality code wise would be very similar to creating new harddisk images, but maybe with a set of 2-3 floppy image sizes depending on what to support: 720kb and 1.4mb floppy images, 360kb maybe.

It would be super awesome if the shortcut function in PMINIT would enable creating floppy images like the ability to switch floppy images.

It's not a critical issue for me and it works fine creating a few blank 1.4mb floppy images in the floppy folder for when it's needed, but I encountered it once and thought it might be worth mentioning here.

**Comment by FreddyVRetro** [comment]
Hi,
New fonctions I will work on in the next 2 months will have all this obsolet :)
I work based on priority, so maybe it will be possible later.
