### ISSUE TITLE
Can't open wifi

### ISSUE THREAD

**Issue by GeCro1950** [FreddyVRetro/ISA-PicoMEM#45]
No matter what I try, I cannot activate the WiFi. 
I keep getting the message Can't open wifi.txt.
My text file is named: wifi.txt
What am I doing wrong?

**Comment by Station2381-sys** [comment]
the file must be in the root of the card.  the first line is the SSID name and the second line is the password.  so check if the wifi.txt file is there.  if you created it in Windows, it can be called wifi.txt.txt.

**Comment by GeCro1950** [comment]
![pico_probleem](https://github.com/user-attachments/assets/1cc381ec-e582-412f-b400-5ae9f880aeb0)
![pico_probleem1](https://github.com/user-attachments/assets/698a9f86-3205-45e7-9ff6-1480a3458cac)

**Comment by Station2381-sys** [comment]
delete the .txt and then you'll be fine.

**Comment by Station2381-sys** [comment]
![inbound5561958119127768466](https://github.com/user-attachments/assets/9da86401-b0db-4155-957a-c87f1561ca51)

**Comment by GeCro1950** [comment]
Thanks Station2183-sys that was the problem....
