### ISSUE TITLE
Recommendations for tool to edit virtual drive images

### ISSUE THREAD

**Issue by kp73** [FreddyVRetro/ISA-PicoMEM#46]
Hi, not an issue as such, but I’d like to be able to take my PicoMem SD card, mount it on my pc and add files to the virtual drive image.  

Any recommendations for tools to do that?

**Comment by xinteksik** [comment]
https://robsmithdev.co.uk/diskflashback

Works for me.

**Comment by FreddyVRetro** [comment]
Hi,
Thanks for the info, It ls a really recent softqware that looks excellent :)
I added it in the Wiki
