### ISSUE TITLE
Feature request: boot from .ISO

### ISSUE THREAD

**Issue by DosWorld** [FreddyVRetro/ISA-PicoMEM#51]
%subj%

**Comment by MicrosoftWorks** [comment]
+1 to the ISO Support! Fiddly mounting of .IMG (Specifically RAW FAT16 Drives) files in Arch-based distros is killing me!

**Comment by FreddyVRetro** [comment]
ISO file support will be there.
Most of the code already exist.

I am not sure at all about ISO Boot, it may be complicated.
I close this request as planned
