### ISSUE TITLE
Feature Request: Raspberry Pi Pico 2

### ISSUE THREAD

**Issue by sdcoil** [FreddyVRetro/ISA-PicoMEM#54]
Excellent job, Freddy!

Will you be adding support for the Pico 2 or the Pico 2 W (when/if it's released)?

Thanks

--Stacy

**Comment by FreddyVRetro** [comment]
Hi,

The problem of the Pico 2 or Pico 2 W is that the feature that will boost the PicoMEM is not possible on them.
(The QSPI PSRAM support)
Then, there will be no advantage to use these boards.

I will check anyway for the Picoroni pico plus 2 or do a board with the RP3520B directly soldered.

So, Yes, but not with the pico boards.

**Comment by sdcoil** [comment]
> Hi,
> 
> The problem of the Pico 2 or Pico 2 W is that the feature that will boost the PicoMEM is not possible on them. (The QSPI PSRAM support) Then, there will be no advantage to use these boards.
> 
> I will check anyway for the Pimoroni pico plus 2 or do a board with the RP3520B directly soldered.
> 
> So, Yes, but not with the pico boards.

Got it. Thank you for the quick reply.

**Comment by hobopanda** [comment]
Hi, 

Looking at the new Pico 2 Data sheet I see that it supports External Quad-SPI flash just like the pico 1

**Comment by FreddyVRetro** [comment]
I Close this one as Pico2 is of course planned :)

**Comment by hobopanda** [comment]
The new by pico has 256K of extra onboard ram so potentially the 128K zero stay memory can be increased to 384K
