### ISSUE TITLE
Force 80 column mode for setup screen

### ISSUE THREAD

**Issue by hvontres** [FreddyVRetro/ISA-PicoMEM#60]
On my Vendex Headstart II, the boot screen switches to 40column mode. This causes the Setup utility to not render correctly. Would it be possible to force the setup screen into 80 column mode?

**Comment by FreddyVRetro** [comment]
Hi,

Last time I tried to play with the Video mode it crashed on my PC so I did put it on the side.

Is it monochrome or color ?
;00  40x25 B/W text
;01  40x25 color text

I just saw that at the end of the setup, PicoMEM try to set the 80x25 color text mode, is it changed when you quit the setup ? (Esc)

**Comment by hvontres** [comment]
40x25 color. And yes, after I exit setup, it goes to 80 column mode, I think.

**Comment by FreddyVRetro** [comment]
Force 89 columns is now added (For next release)

**Comment by hvontres** [comment]
Thank you :)
