### ISSUE TITLE
FPU math cooprocessor emulation?

### ISSUE THREAD

**Issue by Ripper912** [FreddyVRetro/ISA-PicoMEM#61]
Hi, Freddy

Once again thank you for such Superb product, really love it.Was just thinking if its possible as an enhancment for your your PicoMem could possibly emulate also a FPU Math cooprocessor like 287 ect. ?

Thanks

**Comment by FreddyVRetro** [comment]
Hi,

Thanks,

The FPU is directly connected to the CPU, so it is impossible to emulate via ISA.

**Comment by Ripper912** [comment]
Oki thanks a lot...still your device is superb
