### ISSUE TITLE
Allow floppy change over USB for OS installs

### ISSUE THREAD

**Issue by hvontres** [FreddyVRetro/ISA-PicoMEM#63]
It would be nice to have some way to swap Floppy images using the usb port. This would be very helpful for installing dos to a new blank HDD image, since we can't run pminit /k to enable the keyboard shortcut.

**Comment by FreddyVRetro** [comment]
Hi,

DOS Installation is nothing else than file copy.
DOS can be installed via an emulator, like PCEM, it is even much faster like this.
This is how I build my images.
There are videos and tutorials explaining how to do : 
https://www.youtube.com/watch?v=fp76i49rls4

**Comment by FreddyVRetro** [comment]
There is no possibility of buttons for the moment and USB disk support is in progress
