### ISSUE TITLE
I/O Port Failure - no tandy music / emulation.

### ISSUE THREAD

**Issue by user5518** [FreddyVRetro/ISA-PicoMEM#72]
My PicoMem is in a Toshiba T3200 with a 286 12MHz and 1MB RAM (and a ET3000AX with 512KB)  installed, primary for Music emulation.

Adlib and CMS are working fine. But Tandy isn't (anymore). 

For some reason, I sometimes (not always) get an "I/O Port Failure" and the Tandy music in "The Secret of Monkey Island" does not play. I initialized the card with "pminit /tdy 1".

(I started the game with "monkey ts" (no sound), "monkey a" (for adlib) "monkey g" (for cms) oder "monkey i" for the internal speaker are all working fine.)

![IMG_2247](https://github.com/user-attachments/assets/c6d50f90-104d-49bd-815c-1e7ee30a49c3)

What can I do to make Tandy work again?

**Comment by user5518** [comment]
No, not so far. Let me try that, I will report back. Thank you.

**Comment by FreddyVRetro** [comment]
Hi,

The Port failure is normal, it I did not found why PMinit sometimes fail on it, but the port are working.
I checked the PMinit and I forgot to code the tandy initialisation in it :(

Did you try to enable it with the BIOS ?

**Comment by FreddyVRetro** [comment]
Hi again,

On a 286, you can't use the Tandy audio with the normal port, as it is C0 and this is the port for the 2ND DMA Controller

To have Tandy playing on Monkey island, you need to use this default port, the /tdy option configure the port 2C0 and need to have a modified monkey island executable.

You can find infos on all this on vogons forum, posts about the Tandy Board

**Comment by user5518** [comment]
Thank you for your response. I was just try out different ports, and the last one (0C0) is working fine. :)

I was pretty sure 1E0 was working before I replaced the fans in this unit, but now I'm happy, that the tandy music is playing again.

![IMG_2251](https://github.com/user-attachments/assets/e6aea291-d89b-4a2f-843c-36c469617f22)

Now I can try out Wifi, the Harddisk and RAM-feature.

And of course: Thank you very much for your hard work on the PicoMEM, it is a really great piece of hardware.
