### ISSUE TITLE
Cant get new picomem to run on a commodore pc10-3?

### ISSUE THREAD

**Issue by Skynet1HA** [FreddyVRetro/ISA-PicoMEM#76]
Hi there.

(Nothing wrong anyway, see my last message, sorry for the inconvenience)

I have a hard time trying to get my picomem to run on my commodore pc10-3.
When turning the computer on, I dont get the picomem bios texts at all...

I have flashed the latest October FR version on the picomem, and I have tried a lot of different combinations of settings in config.
But nothing works.

What is the trick?
I need a little knowhow to get any further, I think...

All help is highly appreciated.

Kind regards
Peter

**Comment by Skynet1HA** [comment]
Can it perhaps be jumpers on the mainboard that is set incorrect, or perhaps becource i have put in the latest 4.41 bios?

**Comment by Skynet1HA** [comment]
OMG...

It was the MicroRAM card i have instead of working mainboard ram, that I by mistake had set to fill the same address space...

DOH!🤦‍♂️

Now it is working 💪 

It is so nice to finally see the COMMODORE PC20-3  running.
It is actually a PC20-3 i just realized...

And with the latest 4.41 bios.

**Comment by FreddyVRetro** [comment]
Nice,
of course, the best to tst is to remove all the other cards ;)

**Comment by Skynet1HA** [comment]
Yes, but that was not an option, as I have replaced all the faulty ram on
the main board with the ram card...😊

tirs. 3. dec. 2024 11.06 skrev FreddyV ***@***.***>:
