### ISSUE TITLE
PicoMEM issues when shadowed by BIOS

### ISSUE THREAD

**Issue by megatog615** [FreddyVRetro/ISA-PicoMEM#8]
I decided to try shadowing D000, and, 
- the setup screen for the PicoMEM has corrupt display.
- Issuing ctrl-alt-del, entering the BIOS setup and disabling shadowing seems to crash the firmware(no longer loads after POST). Cold boot fixes it.

I'm sure some other features function unpredictably when it's shadowed.

**Comment by FreddyVRetro** [comment]
Hi,

It is normal that the shadow bread the PicoMEM.
The PicoMEM need emulated ROM and RAM to work.
When shadow is enabled, the RAM will no more be the emulated RAM, but the computer one, then, the communication between the PC and the Pico is lost.
Anyway, if you can enable only 16kb of Shadow, it should work.

**Comment by FreddyVRetro** [comment]
Normal behaviour
